#!/bin/bash

brew update
brew install git
brew upgrade
brew install \
    mutt \
    zsh \
    yajl \
    coreutils \
    findutils \
    bash \
    bash-completion \
    grc \
    tmux \
    ack \
    gibo \
    curl \
    ffmpeg \
    imagemagick \
    lynx \
    tree \
    unrar \
    watch \
    the_silver_searcher

# Remove outdated versions from the cellar
brew cleanup
# Symlink applications into the /Applications dir
brew linkapps

# Install native apps
brew tap phinze/homebrew-cask
brew install brew-cask

function installcask() {
    brew cask install "${@}" 2> /dev/null
}

installcask dropbox
installcask google-chrome
installcask google-chrome-canary
installcask imagealpha
installcask imageoptim
installcask iterm2
# brew install macvim is good enough
#installcask macvim
installcask miro-video-converter
installcask sublime-text
installcask the-unarchiver
installcask tor-browser
installcask transmission
installcask ukelele
installcask virtualbox
installcask vlc
