#! /usr/bin/env python

import sys, gzip, subprocess
from time import strftime

timestring = strftime("%Y-%m-%d_%H-%M")

#Backup all of the local databases
def dump_db():
    db_user = "root"
    db_pass = "nadrojlee"
    out_filename = "DB_allen_all_" + timestring + ".sql.gz"

    cmdL1 = ["mysqldump", "--user=" + db_user, "--password=" + db_pass, "--all-databases"]

    p1 = subprocess.Popen(cmdL1, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    dump_output = p1.communicate()[0]

    f = gzip.open(out_filename, "wb")
    f.write(dump_output)
    f.close()

if len(sys.argv) < 2:
    print "Missing argument"
elif sys.argv[1] == "db":
    dump_db()

